Repository omc-college/management-system, pull requests merged in 2020-05, with the labels that each got.

#9 handlers for RBAC CRUD service were implemented
  .gitignore
  api/rbac/rbac-api.yaml
  cmd/rbac/main.go
  go.mod
  go.sum
  pkg/rbac/api/handlers/crud_handlers.go
  pkg/rbac/api/routers/router.go
  pkg/rbac/models/error.go
  pkg/rbac/models/role.go
  pkg/rbac/repository/postgres/errors.go
  pkg/rbac/repository/postgres/migrations/000001_init.down.sql
  pkg/rbac/repository/postgres/migrations/000001_init.up.sql
  pkg/rbac/repository/postgres/postgres.go
  pkg/rbac/repository/postgres/role.go
Labels: RBAC Service, enhancement

#11 Example of auntintification for Post to ims-api.yaml was added
  api/ims/ims-api.yaml
Labels: Identity management Service, enhancement

#8 timetabling service OpenApi specification
  api/timetable/timetable.yml
Labels: Timetabling service, enhancement

#20 issue 19, added OpenAPI spec. for User and Group Management
  api/ugm/ugm.yaml
Labels: Users and Groups Service, enhancement

#26 Sign Up Flow API
  api/ims/ims-api.yaml
Labels: Identity management Service, enhancement

#29 SQL-scripts for SignUp
  pkg/signup/repository/postgresql/migrations/SignUp_init.down.sql
  pkg/signup/repository/postgresql/migrations/SignUp_init.up.sql
Labels: Identity management Service, enhancement

#22 issue-21, utility that generates Role Template based on given array of Open API specs was created
  .gitignore
  Makefile
  README.md
  api/rbac/rbac-api.yaml
  cmd/rbac/main.go
  cmd/rbacgen/README.md
  cmd/rbacgen/main.go
  cmd/rbacgen/roleTmpl.yaml
  cmd/rbacgen/timetableApi.yaml
  go.mod
  go.sum
  pkg/rbac/api/handlers/crud_handlers.go
  pkg/rbac/api/routers/router.go
  pkg/rbac/models/role.go
  pkg/rbac/openapi/openapi.go
  pkg/rbac/openapi/roleTmpl.go
  pkg/rbac/repository/postgres/migrations/000002_init.down.sql
  pkg/rbac/repository/postgres/migrations/000002_init.up.sql
  pkg/rbac/repository/postgres/postgres.go
  pkg/rbac/repository/postgres/role.go
Labels: RBAC Service, enhancement

#40 Renamed folder signup to ims, sql .up and .down files. Added model and sql script with access_tokens
  api/ims/ims-api.yaml
  go.mod
  go.sum
  pkg/ims/models/models.go
  pkg/ims/repository/postgresql/migrations/000001_create_users_table.down.sql
  pkg/ims/repository/postgresql/migrations/000001_create_users_table.up.sql
  pkg/ims/repository/postgresql/migrations/000002_create_acsess_token.down.sql
  pkg/ims/repository/postgresql/migrations/000002_create_acsess_token.up.sql
Labels: Identity management Service, enhancement

#53 Adding new features for UI
  ui/src/app/app.module.ts
  ui/src/app/calendar/calendar.component.ts
  ui/src/app/header/header.component.html
  ui/src/app/header/header.component.sass
  ui/src/app/header/header.component.ts
  ui/src/app/in-memory-data.service.ts
  ui/src/app/mock-groups.ts
  ui/src/app/mock-lessons.ts
  ui/src/app/mock-rooms.ts
  ui/src/app/mock-subjects.ts
  ui/src/app/mock-users.ts
  ui/src/app/models/Error.ts
  ui/src/app/models/Group.ts
  ui/src/app/models/Lesson.ts
  ui/src/app/models/Room.ts
  ui/src/app/models/Subject.ts
  ui/src/app/models/User.ts
  ui/src/app/shared/timetable-http-service.service.spec.ts
  ui/src/app/shared/timetable-http.service.ts
  ui/src/app/sidebar/sidebar.component.html
  ui/src/app/sidebar/sidebar.component.ts
  ui/src/app/slider-menu/slider-menu.component.html
  ui/src/app/slider-menu/slider-menu.component.sass
  ui/src/app/slider-menu/slider-menu.component.spec.ts
  ui/src/app/slider-menu/slider-menu.component.ts
  ui/src/app/timestamp1.ts
  ui/src/app/timestamp2.ts
  ui/src/app/timetable.service.ts
  ui/src/app/timetable/timetable.component.html
  ui/src/app/timetable/timetable.component.sass
  ui/src/app/timetable/timetable.component.ts
  ui/src/styles.sass
Labels: Timetabling service, enhancement

#51 issue-50, removed business logic from handlers to service package
  pkg/rbac/api/handlers/crud_handlers.go
  pkg/rbac/api/routers/router.go
  pkg/rbac/service/service.go
Labels: RBAC Service, enhancement

#47 issue-46, configured DB connection for RBAC service using pkg/config
  Makefile
  cmd/rbac/config.go
  cmd/rbac/main.go
  cmd/rbac/rbac-service-example-config.yaml
  cmd/rbacgen/config.go
  cmd/rbacgen/main.go
  cmd/rbacgen/rbacgen-service-example-config.yaml
  cmd/rbacgen/roleTmpl.yaml
  go.mod
  go.sum
  pkg/config/config.go
  pkg/db/config.go
  pkg/rbac/repository/postgres/postgres.go
Labels: RBAC Service, enhancement

#61 issue-59, implemented authorization middleware using Mux
  .gitignore
  go.mod
  go.sum
  pkg/rbac/api/middleware/authorizationCache.json
  pkg/rbac/api/middleware/middleware.go
  pkg/rbac/api/routers/router.go
  pkg/rbac/opa/authorization.rego
  pkg/rbac/opa/opa.go
Labels: RBAC Service, enhancement

#38 Create postgres.go (SIgnUp)
  pkg/ims/models/models.go
  pkg/ims/repository/postgresql/migrations/000003_add_email_const.up.sql
  pkg/ims/repository/postgresql/postgres.go
Labels: Identity management Service, enhancement

#58 add mat-datepicker
  ui/angular.json
  ui/package-lock.json
  ui/package.json
  ui/src/app/app.module.ts
  ui/src/app/calendar/calendar.component.html
  ui/src/app/calendar/calendar.component.sass
  ui/src/app/calendar/calendar.component.ts
  ui/src/app/header/header.component.html
  ui/src/app/header/header.component.sass
  ui/src/app/header/header.component.ts
  ui/src/app/in-memory-data.service.ts
  ui/src/app/models/Lesson.ts
  ui/src/app/sidebar/error.html
  ui/src/app/sidebar/sidebar.component.html
  ui/src/app/sidebar/sidebar.component.sass
  ui/src/app/sidebar/sidebar.component.ts
  ui/src/app/slider-menu/slider-menu.component.html
  ui/src/app/slider-menu/slider-menu.component.sass
  ui/src/app/slider-menu/slider-menu.component.ts
  ui/src/app/timetable.service.ts
  ui/src/app/timetable/timetable.component.html
  ui/src/app/timetable/timetable.component.sass
  ui/src/app/timetable/timetable.component.ts
  ui/src/custom-theme.scss
  ui/src/index.html
  ui/src/styles.sass
Labels: Timetabling service

#72 issue-68, implemented functions from repository/postgres as RolesRepository's methods
  .gitignore
  cmd/rbacgen/main.go
  pkg/rbac/repository/postgres/postgres.go
  pkg/rbac/service/service.go
Labels: RBAC Service, enhancement

#79 Issue 80, SQL script `000003_add_email_const.down.sql` was created.
  pkg/ims/repository/postgresql/migrations/000003_add_email_const.down.sql
Labels: Identity management Service, enhancement

#74 implemention mq with rbac service
  cmd/rbac/main.go
  go.mod
  go.sum
  pkg/pubsub/client.go
  pkg/pubsub/envelope.go
  pkg/rbac/api/handlers/crud_handlers.go
  pkg/rbac/api/routers/router.go
  pkg/rbac/models/consts.go
  pkg/rbac/service/service.go
Labels: MQ, enhancement

#86 Creation of search-result component
  ui/src/app/app.component.html
  ui/src/app/app.component.sass
  ui/src/app/app.component.ts
  ui/src/app/app.module.ts
  ui/src/app/calendar/calendar.component.ts
  ui/src/app/header/header.component.html
  ui/src/app/header/header.component.sass
  ui/src/app/header/header.component.ts
  ui/src/app/in-memory-data.service.ts
  ui/src/app/models/Lesson.ts
  ui/src/app/search-result/search-result.component.html
  ui/src/app/search-result/search-result.component.sass
  ui/src/app/search-result/search-result.component.spec.ts
  ui/src/app/search-result/search-result.component.ts
  ui/src/app/shared/timetable-http.service.ts
  ui/src/app/sidebar/sidebar.component.html
  ui/src/app/sidebar/sidebar.component.sass
  ui/src/app/sidebar/sidebar.component.ts
  ui/src/app/slider-menu/delete-dialog.html
  ui/src/app/slider-menu/slider-menu.component.html
  ui/src/app/slider-menu/slider-menu.component.sass
  ui/src/app/slider-menu/slider-menu.component.ts
  ui/src/app/slider-menu/success-dialog.html
  ui/src/app/timetable.service.ts
  ui/src/app/timetable/timetable.component.html
  ui/src/app/timetable/timetable.component.sass
  ui/src/app/timetable/timetable.component.ts
  ui/src/styles.sass
Labels: Timetabling service, enhancement

#93 Issue-92, Hash and Salt functions created
  pkg/pwd/hash.go
  pkg/pwd/random.go
Labels: Identity management Service, enhancement

#62 Issue 42 Added functions for identifying the user by email, retrieving information about him and saving the token for ims service
  go.mod
  go.sum
  pkg/ims/models/models.go
  pkg/ims/repository/postgresql/credentials_repository.go
  pkg/ims/repository/postgresql/migrations/000005_re-creation_role.down.sql
  pkg/ims/repository/postgresql/migrations/000005_re-creation_role.up.sql
  pkg/ims/repository/postgresql/postgres.go
  pkg/ims/repository/postgresql/signup_repository.go
  pkg/ims/repository/postgresql/type.go
  pkg/ims/repository/postgresql/users_repository.go
Labels: Identity management Service, enhancement
